media:
  input: public/media
  output: /media
content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    filename: "{year}-{month}-{day}-{primary}.md"
    view:
      fields: [title, category, date, draft]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: excerpt
        label: Excerpt
        type: text
        required: true
        options:
          minlength: 20
          maxlength: 220
      - name: date
        label: Publish date
        type: date
        required: true
      - name: category
        label: Category
        type: select
        options:
          values:
            - Cars
            - Technology
            - Tutorials
            - Minecraft
            - Notes
      - name: status
        label: Status
        type: string
        required: false
      - name: tags
        label: Tags
        type: select
        options:
          multiple: true
          values:
            - subaru
            - legacy
            - audio
            - electronics
            - tutorial
            - minecraft
            - homelab
            - tools
            - notes
      - name: coverImage
        label: Cover image
        type: image
        required: false
      - name: draft
        label: Draft
        type: boolean
        required: false
      - name: body
        label: Body
        type: rich-text
