title: Bluemethyst Blog
description: Notes, repairs, and projects.
url: "https://bluemethyst.github.io"
baseurl: "/blog"

markdown: kramdown

defaults:
  - scope:
      path: "content/posts"
      type: "pages"
    values:
      layout: "post"
